on:
  push:
    branches:
      - main  # Ajusta la rama según sea necesario

name: deploy

jobs:
  deploy_to_cluster:  # Nombre del trabajo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tags: |
            latest
            ${{ github.sha }}
