name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_cluster:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Login a DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Build y push de la imagen a DockerHub
      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            bry5co/ci-cd:latest
            bry5co/ci-cd:${{ github.sha }}

      # Paso 4: Configuración de kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.2'

      # Paso 5: Crear y configurar kubeconfig desde los secretos de GitHub
      - name: Create kubeconfig from GitHub Secret
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
          echo "$KUBE_CA_CERT" > $HOME/.kube/ca.crt
          echo "$KUBE_CLIENT_CERT" > $HOME/.kube/client.crt
          echo "$KUBE_CLIENT_KEY" > $HOME/.kube/client.key
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}
          KUBE_CLIENT_CERT: ${{ secrets.KUBE_CLIENT_CERT }}
          KUBE_CLIENT_KEY: ${{ secrets.KUBE_CLIENT_KEY }}

      # Paso 6: Verificar configuración de Kubernetes
      - name: Check Kubernetes config
        run: |
          kubectl config view
          kubectl cluster-info

      # Paso 7: Desplegar en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-app-deployment my-container=bry5co/ci-cd:latest
          kubectl rollout restart deployment/my-app-deployment
