name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches:
      - main  # Este pipeline se ejecutará solo cuando se realice un push a la rama principal (main)

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Usamos Ubuntu como entorno de ejecución

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Loguearse a DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Añadir tu usuario en secrets de GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Añadir tu contraseña en secrets de GitHub

      # Paso 3: Construir y Push de la imagen Docker a DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # El contexto es el directorio del repositorio
          file: ./Dockerfile  # Ruta del Dockerfile que se usará para construir la imagen
          push: true  # Se empujará la imagen a DockerHub
          tags: |
            bry5co/ci-cd:latest
            bry5co/ci-cd:${{ github.sha }}

  deploy_to_kubernetes:
    runs-on: ubuntu-latest  # Usamos Ubuntu como entorno de ejecución
    needs: build_and_push  # Este job depende del anterior para construirse

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configuración de kubectl (suponiendo que Docker Desktop está habilitado con Kubernetes)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.2'  # Puedes cambiar la versión si lo necesitas

      # Paso 3: Verificar conectividad con el clúster Kubernetes de Docker Desktop
      - name: Check Kubernetes cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      # Paso 4: Desplegar la imagen Docker en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-app-deployment my-container=bry5co/ci-cd:latest
          kubectl rollout restart deployment/my-app-deployment
