on:
  push:
    branches:
      - main

name: deploy

jobs:
  deploy_to_cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            bry5co/ci-cd:latest
            bry5co/ci-cd:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.2'

      - name: Configure Kubernetes access
        run: |
          # Decodificar secretos base64 a archivos
          echo "$KUBE_CA_CRT" | base64 -d > ca.crt
          echo "$KUBE_CLIENT_CRT" | base64 -d > client.crt
          echo "$KUBE_CLIENT_KEY" | base64 -d > client.key
          mkdir -p ~/.kube
          echo "
          apiVersion: v1
          clusters:
            - cluster:
                certificate-authority: $(pwd)/ca.crt
                server: https://172.31.93.137:8443
              name: minikube
          contexts:
            - context:
                cluster: minikube
                user: minikube
              name: minikube
          current-context: minikube
          kind: Config
          users:
            - name: minikube
              user:
                client-certificate: $(pwd)/client.crt
                client-key: $(pwd)/client.key
          " > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          # Actualizar la imagen del contenedor en el despliegue
          kubectl set image deployment/my-app-deployment my-container=bry5co/ci-cd:latest
          # Reiniciar el despliegue para aplicar cambios
          kubectl rollout restart deployment/my-app-deployment
